---
repos:
  - repo: https://gitlab.corp.redhat.com/infosec-public/developer-workbench/tools.git
    rev: rh-pre-commit-2.2.0
    hooks:
      # If you have not run this hook on your system before, it may prompt you to
      # log in for patterns, and you will need to try again.
      #
      # Docs: https://source.redhat.com/departments/it/it-information-security/leaktk/leaktk_components/rh_pre_commit
      - id: rh-pre-commit
      # - id: rh-pre-commit.commit-msg # Optional for commit-msg attestation

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-yaml
